name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'Dockerfile'
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.ts'
      - '**/*.tsx'
      - '.github/workflows/**'
  workflow_dispatch:

env:
  IMAGE_NAME: shoyo-hostable
  DOCKERHUB_REPO: blaziumengine/shoyo-hostable

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image with Debug Output
        id: docker_build
        run: |
          echo "Building image: $DOCKERHUB_REPO:latest"
          docker build --progress=plain -t $DOCKERHUB_REPO:latest .
        continue-on-error: false

      - name: Test Docker Image
        run: |
          echo "Testing docker image startup..."
          docker run --rm -e PAGE_UID=test -e PUBLIC_KEY=test $DOCKERHUB_REPO:latest sh -c "echo Image started successfully"
        continue-on-error: false

      - name: Push Docker Image to DockerHub
        if: ${{ success() }}
        run: |
          echo "Pushing image to Docker Hub: $DOCKERHUB_REPO:latest"
          docker push $DOCKERHUB_REPO:latest

      - name: Log Success
        run: echo "Workflow completed successfully for image $DOCKERHUB_REPO"

      - name: Handle Failure
        if: ${{ failure() }}
        run: echo "Build or test failed for image $DOCKERHUB_REPO"
